name: Authentication CI CD

on:
    push:
        branches:
            - main

jobs:
    build-test:
        name: Build and Testing the project
        runs-on: ubuntu-22.04
        steps:
            - name: Checking out the code
              uses: actions/checkout@v4

            - name: Setup NodeJS v23.7.0
              uses: actions/setup-node@v4

            - name: Start MySQL server using docker
              run: |
                  docker run -d --name mysql-server -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=authentication -p 3306:3306 mysql:8.0

            - name: Install dependencies
              run: cd service && npm install

            - name: Change the .github.env file to .env
              run: cd service && cp .github.env .env && cat .env

            - name: Run tests
              run: cd service && npm run test
