name: Authentication CI CD

on:
    push:
        branches:
            - main

jobs:
    build-test:
        name: Build and Testing the project
        runs-on: ubuntu-22.04
        steps:
            - name: Checking out the code
              uses: actions/checkout@v4

            - name: Setup NodeJS v23.7.0
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: cd service && npm install

            - name: Install MySQL
              run: |
                  sudo apt-get update
                  sudo apt-get install -y mysql-server

            - name: Start MySQL
              run: |
                  sudo service mysql start

            - name: Change the root password
              run: |
                  sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1233456';"

            - name: Create database
              run: |
                  mysql -u root -p1233456 -e "CREATE DATABASE authentication"

            - name: Change the .github.env file to .env
              run: cd service && cp .github.env .env && cat .env

            - name: Run tests
              run: cd service && npm run test
