name: Authentication CI CD

on:
    push:
        branches:
            - main

jobs:
    build-test:
        name: Build and Testing the project
        runs-on: ubuntu-22.04
        steps:
            - name: Checking out the code
              uses: actions/checkout@v4

            - name: Setup NodeJS v23.7.0
              uses: actions/setup-node@v4

            - name: Start MySQL server using docker
              run: |
                  docker run -d --name mysql-server -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=authentication -p 3306:3306 mysql:8.0

            - name: Install dependencies
              run: cd service && npm install

            - name: Change the .github.env file to .env
              run: cd service && cp .github.env .env && cat .env

            - name: Run tests
              run: cd service && npm run test

    deploy:
        name: Deploy the project
        runs-on: ubuntu-22.04
        # needs: build-test
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.VPS_SSH_PRIVATE}}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{secrets.VPS_IP}} >> ~/.ssh/known_hosts

            - name: Deploy to the VPS
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{secrets.VPS_IP}}
                  username: root
                  key: ${{secrets.VPS_SSH_PRIVATE}}
                  script: |
                      rm -r ntt-authentication
                      git clone https://github.com/threezinedine/ntt-authentication.git
                      cd ntt-authentication/service
                      rm .env
                      echo "HOST=0.0.0.0\nPORT=8080\nMYSQL_HOST=${{secrets.MYSQL_HOST}}\nMYSQL_PORT=${{secrets.MYSQL_PORT}}\nMYSQL_USER=${{secrets.MYSQL_USER}}\nMYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}\nMYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}\nMODE=production" > .env
                      cat .env
                      docker compose up -d

            # - name: Connect to the VPS
            #   run: |
            #       ssh -i ~/.ssh/id_rsa ${{secrets.VPS_ACCOUNT}}@${{secrets.VPS_IP}} << 'EOF'
            #       rm -r ntt-authentication
            #       git clone https://github.com/threezinedine/ntt-authentication.git
            #       cd ntt-authentication/service
            #       rm .env
            #       echo "HOST=0.0.0.0\nPORT=8080\nMYSQL_HOST=${{secrets.MYSQL_HOST}}\nMYSQL_PORT=${{secrets.MYSQL_PORT}}\nMYSQL_USER=${{secrets.MYSQL_USER}}\nMYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}\nMYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}\nMODE=production" > .env
            #       cat .env
            #       docker compose up -d
            #       EOF
            #   shell: bash
